update download artifacts

diff --git a/.github/workflows/SystemStage.yml b/.github/workflows/SystemStage.yml
--- a/.github/workflows/SystemStage.yml
+++ b/.github/workflows/SystemStage.yml
@@ -18,52 +18,54 @@ jobs:
         with:
           node-version: 20
 
-      - name: Install dependencies
-        run: npm ci
+      # - name: Install dependencies
+      #   run: npm ci
 
-      - name: Install MongoDB
-        run: |
-          echo "Installing MongoDB..."
-          brew tap mongodb/brew
-          brew install mongodb-community@6.0
+      # - name: Install MongoDB
+      #   run: |
+      #     echo "Installing MongoDB..."
+      #     brew tap mongodb/brew
+      #     brew install mongodb-community@6.0
 
-      - name: Start MongoDB
-        run: |
-          echo "Starting MongoDB..."
-          brew services start mongodb/brew/mongodb-community@6.0
-          echo "Waiting for MongoDB to be ready..."
-          until nc -z localhost 27017; do
-            echo "MongoDB is not ready yet, retrying in 5 seconds..."
-            sleep 5
-          done
+      # - name: Start MongoDB
+      #   run: |
+      #     echo "Starting MongoDB..."
+      #     brew services start mongodb/brew/mongodb-community@6.0
+      #     echo "Waiting for MongoDB to be ready..."
+      #     until nc -z localhost 27017; do
+      #       echo "MongoDB is not ready yet, retrying in 5 seconds..."
+      #       sleep 5
+      #     done
 
-      - name: Create test database and collection
-        run: |
-          echo "Creating test database and collection..."
-          mongosh <<EOF
-          use test
-          db.test.insertMany([
-            { name: "test1", value: 1 },
-            { name: "test2", value: 2 },
-            { name: "test3", value: 3 }
-          ])
-          EOF
+      # - name: Create test database and collection
+      #   run: |
+      #     echo "Creating test database and collection..."
+      #     mongosh <<EOF
+      #     use test
+      #     db.test.insertMany([
+      #       { name: "test1", value: 1 },
+      #       { name: "test2", value: 2 },
+      #       { name: "test3", value: 3 }
+      #     ])
+      #     EOF
 
       - name: Download Artifacts
         uses: actions/download-artifact@v4
         with:
-          pattern: "*.dmg"
+          # name: MongoDB Query Executor
           repository: vaisakhsasikumar/my-electron-app
 
-      - name: Mount DMG
-        run: |
-          dmg_file=$(find . -maxdepth 1 -name '*.dmg' | head -n 1)
-          if [ -n "$dmg_file" ]; then
-              hdiutil attach "$dmg_file" -nobrowse -quiet
-          else
-              echo "No .dmg file found in the current directory."
-              exit 1
-          fi
+      - run: ls -R
+
+      # - name: Mount DMG
+      #   run: |
+      #     dmg_file=$(find . -maxdepth 1 -name '*.dmg' | head -n 1)
+      #     if [ -n "$dmg_file" ]; then
+      #         hdiutil attach "$dmg_file" -nobrowse -quiet
+      #     else
+      #         echo "No .dmg file found in the current directory."
+      #         exit 1
+      #     fi
 
       - name: Set Permissions
         # Allow execute pipeline script
